### ISSUE TITLE
Plugin doesn't load after lastest update 

### ISSUE THREAD

**Issue by alincupunct** [komashchenko/ServerAccount#1]
Console output - meta load server_account.so
Failed to load plugin server_account.so (File not found: /server_account.so).
meta load server_account
Failed to load plugin server_account (File not found: /server_account.so).

This only happens after the last update (it worked before restarting my server, files are there)

**Comment by freakexeuLow** [comment]
> Console output - meta load server_account.so Failed to load plugin server_account.so (File not found: /server_account.so). meta load server_account Failed to load plugin server_account (File not found: /server_account.so).
> 
> This only happens after the last update (it worked before restarting my server, files are there)

hey and pls try the new metamod version 1225 : [https://www.sourcemm.net/downloads.php?branch=dev](https://www.sourcemm.net/downloads.php?branch=dev)

Edit: is it fixed for you, pls close the issue 👍🏼
